### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 500: 500

### ISSUE THREAD

**Issue by liqy233** [TaufiqHassan/acccmip6#16]
Hello,
I use conda to install acccmip6.
However,I run the command:
acccmip6 -o S -m CanESM5 -e ssp245,hist-piAer -v vas,zg -f mon  
It turns out:
(wrf4palm1.0) lqy@DESKTOP-LR1ELST:~$ acccmip6 -o S -m CanESM5 -e ssp245,hist-piAer -v vas,zg -f mon

TIPS: Use the check (-c) argument to check your inputs.
Traceback (most recent call last):
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/bin/acccmip6", line 11, in <module>
    sys.exit(main())
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/site-packages/acccmip6/cli.py", line 47, in main
    SearchCmip6(model=model, experiment=experiment, variable=variable, frequency=frequency, realm=realm, check=check, desc=desc, year=year, time=time, rlzn=rlzn, node=node, skip=skipped, cr=cr, set_server=server)
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/site-packages/acccmip6/access_cm.py", line 117, in SearchCmip6
    info = search.get_info()
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/site-packages/acccmip6/utilities/c6db.py", line 141, in get_info
    info = _extract_info(self._var, self._mod, self._realm, self._exp, self._freq, self.n_files, self.rlzn, self.year,self.links, node=self.nd, set_server=self.set_server)._get_info()
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/site-packages/acccmip6/utilities/util.py", line 244, in _get_info
    links=_Construct_urls(self.var, self.mod, self.realm, self.exp, self.freq, node=self.node, set_server=self.set_server)._get_wget(0)
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/site-packages/acccmip6/utilities/util.py", line 186, in _get_wget
    urllib.request.urlretrieve(url, str(dir_path))
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/lqy/anaconda3/envs/wrf4palm1.0/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: 500
May I ask you how to slove?
Thanks for your time

**Comment by TaufiqHassan** [comment]
Hello, it was most likely an internal server problem. 

It's working on my end:

`acccmip6 -o S -m CanESM5 -e ssp245,hist-piAer -v vas,zg -f mon`

```
TIPS: Use the check (-c) argument to check your inputs.


 Currently available models based on your search:

 ['CanESM5']

Currently available variables based on your search:

 ['vas', 'zg']

Currently available experiments based on your search:

 ['ssp245']



Number of files: 140



Available realizations: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]




       <===============Exiting now!================>
```

**Comment by CGL5230** [comment]
same issue. I  fall this issue in [July](https://github.com/TaufiqHassan/acccmip6/issues/19). I still don't know how to solve.
